### ISSUE TITLE
Project (Vue/Vite/TypeScript/Tailwind) failing to build with Scoped Preflight

### ISSUE THREAD

**Issue by markywildtype** [Roman86/tailwindcss-scoped-preflight#63]
**Describe the bug**
I am working on a project with a moderately complicated Vue/Vite/TypeScript/Tailwind setup and trying to get scoped Preflight working, but when running `npm run build`, I get a big error:

```
"readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs".
file: /var/www/tpf/node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs:3:9
1: import { withOptions } from 'tailwindcss/plugin.js';
2: import postcss from 'postcss';
3: import { readFileSync } from 'fs';
            ^
4:
5: const optionsHandlerForIgnoreAndRemove = (selector, {
error during build:
RollupError: "readFileSync" is not exported by "__vite-browser-external", imported by "node_modules/tailwindcss-scoped-preflight/dist/plugin.modern.mjs".
    at error (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:13716:16)
    at Module.traceVariable (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:14146:29)
    at ModuleScope.findVariable (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:12589:39)
    at ReturnValueScope.findVariable (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ReturnValueScope.findVariable (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:8309:40)
    at CallExpression.bind (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///var/www/tpf/node_modules/rollup/dist/es/shared/node-entry.js:9875:15)
```

**To Reproduce**
I have attempted to reproduce it on StackBlitz - this was a working Tailwind installation prior to adding scoped preflight. It gives a different error: `[plugin:vite:css] [postcss] require is not defined` - that seems like it _might_ be related. Regardless I am unsure how to get past it. My team lead thinks there may be some shenanigans relating to ESM/CJS etc somewhere but we've had no luck fixing it ourselves.

[StackBlitz ](https://stackblitz.com/edit/vitejs-vite-yh35ar?file=tailwind.config.ts)

**Expected behaviour**
The project to build!

**Screenshots**
If it helps to understand the issue - please attach.

**Desktop (please complete the following information):**
 - Mac OS 15.0.1
 - Chrome (up to date - Version 130.0.6723.117)

**Comment by Roman86** [comment]
Hi @markywildtype ! Did you have a chance to check the proposed solution?
